version: '3'
services:
  test:
    container_name: integration-test-image
    build:
      context: ./
      dockerfile: ./docker/test/Dockerfile
  
  api:
    container_name: api-image
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    # volumes:
    #   - .:/app
    